// lib/tasks/models/task.dart

import 'package:hive/hive.dart';

part 'task.g.dart'; // generated by build_runner

@HiveType(typeId: 2)
enum RepeatOption {
  @HiveField(0)
  none,
  @HiveField(1)
  daily,
  @HiveField(2)
  weekly,
  @HiveField(3)
  monthly,
  @HiveField(4)
  custom
}

@HiveType(typeId: 3)
enum TaskCategory {
  @HiveField(0)
  home,
  @HiveField(1)
  work,
  @HiveField(2)
  study,
  @HiveField(3)
  shopping,
  @HiveField(4)
  other
}

@HiveType(typeId: 1)
class Task extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  String title;

  @HiveField(2)
  DateTime? dueDate;

  @HiveField(3)
  String? dueTime; // stored as "HH:mm" string

  @HiveField(4)
  RepeatOption repeatOption;

  @HiveField(5)
  TaskCategory category;

  @HiveField(6)
  bool isCompleted;

  @HiveField(7)
  final DateTime createdAt;

  @HiveField(8)
  final String languageId; // 'en', 'ur', 'roman_ur'

  @HiveField(9)
  bool isSyncedToFirestore;

  @HiveField(10)
  int reminderOffsetMinutes; // 0 = on time, 15 = 15m before, 60 = 1h before, 1440 = 1d before, -1 = no reminder

  Task({
    required this.id,
    required this.title,
    this.dueDate,
    this.dueTime,
    this.repeatOption = RepeatOption.none,
    this.category = TaskCategory.other,
    this.isCompleted = false,
    required this.createdAt,
    required this.languageId,
    this.isSyncedToFirestore = false,
    this.reminderOffsetMinutes = 15,
  });

  Map<String, dynamic> toFirestore() => {
        'id': id,
        'title': title,
        'dueDate': dueDate?.toIso8601String(),
        'dueTime': dueTime,
        'repeatOption': repeatOption.name,
        'category': category.name,
        'isCompleted': isCompleted,
        'createdAt': createdAt.toIso8601String(),
        'languageId': languageId,
        'reminderOffsetMinutes': reminderOffsetMinutes,
      };

  factory Task.fromFirestore(Map<String, dynamic> data) => Task(
        id: data['id'] as String,
        title: data['title'] as String,
        dueDate: data['dueDate'] != null
            ? DateTime.parse(data['dueDate'] as String)
            : null,
        dueTime: data['dueTime'] as String?,
        repeatOption: RepeatOption.values.firstWhere(
          (e) => e.name == data['repeatOption'],
          orElse: () => RepeatOption.none,
        ),
        category: TaskCategory.values.firstWhere(
          (e) => e.name == data['category'],
          orElse: () => TaskCategory.other,
        ),
        isCompleted: data['isCompleted'] as bool? ?? false,
        createdAt: DateTime.parse(data['createdAt'] as String),
        languageId: data['languageId'] as String? ?? 'en',
        reminderOffsetMinutes: data['reminderOffsetMinutes'] as int? ?? 15,
      );
}
